spec/factories/users.rb, spec/features/user_registration_process_spec.rb
Added feature test for user registration.
=> Registration Feature

app/controllers/users_controller.rb, app/views/users/new.html.erb, config/routes.rb, spec/features/guest_user_can_register_spec.rb
- Created users#show and users#new.
=> Added users controller with the new and create actions.

Gemfile, Gemfile.lock, app/controllers/activation_controller.rb, app/models/user.rb, config/routes.rb, db/migrate/20180514220000_add_password_digest_and_actvated_to_users.rb, db/schema.rb, spec/controllers/activation_controller_spec.rb, spec/factories/users.rb, spec/features/user_registration_process_spec.rb
Added 
bcrypt functionality
activiation controller
Changed
added password_digest to users table
added activated to users table
=> User Model Additions

app/controllers/users_controller.rb, app/mailers/user_mailer.rb, app/views/user_mailer/registration_email.html.erb, app/views/user_mailer/registration_email.txt.erb, config/routes.rb, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/user_mailer_spec.rb
Added dashboard route and create, show actions for the users controller.
=> User Controller

app/controllers/users_controller.rb, app/views/users/show.html.erb
Added show view for the guest user registration.
=> Created passing test for the guest user registration.

app/controllers/sessions_controller.rb, app/controllers/users/activation_controller.rb, app/views/users/activation/edit.html.erb, app/views/users/activation/show.html.erb, config/routes.rb, spec/controllers/sessions_controller_spec.rb, spec/features/user_registration_process_spec.rb
Fixed a broken test
Added a blank sessions controller
=> Fixed broken test

.gitignore, Gemfile, Gemfile.lock, app/views/user_mailer/registration_email.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20180515085044_add_api_key_to_users.rb, db/schema.rb, spec/factories/users.rb, spec/fixtures/user_mailer/activation.html, spec/fixtures/user_mailer/activation.txt, spec/mailers/user_mailer_spec.rb
Added conditionals to user show
Added API key to users table
Created fixtures for the mailers (need to incorporate those)
Added additional assertions to the user mailer spec test
Added figaro gem
Added sendgrid gem
=> Sendgrid functionality

app/controllers/users_controller.rb, app/mailers/application_mailer.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/views/user_mailer/registration_email.html.erb, app/views/user_mailer/registration_email.txt.erb, config/application.rb, spec/mailers/user_mailer_spec.rb
Added ENV for api_key, development and production (BASE URL)
=> Added environment variables

db/migrate/20180515145721_add_default_activation_to_users.rb, db/schema.rb
made migration to set the users default activation to false
=> Default Activation

app/controllers/users/activation_controller.rb, app/mailers/user_mailer.rb, app/models/user.rb, config/routes.rb, spec/mailers/user_mailer_spec.rb, spec/models/user_spec.rb
Cleaned up some of the routes and relevant dependencies.
=> Path Cleanup

app/controllers/api/v1/games/ships_controller.rb, app/controllers/api/v1/games_controller.rb, app/models/game.rb, config/routes.rb
Made some progress in the spec harness.
=> Spec harness

app/controllers/api/v1/games/ships_controller.rb, app/controllers/api/v1/games/shots_controller.rb, app/services/ship_placer.rb, app/services/turn_processor.rb, app/services/values/ship.rb, app/services/values/space.rb
Added params to the ship class.
=> Ship Class

app/controllers/api/v1/games/shots_controller.rb, app/models/game.rb, app/services/turn_processor.rb
Added checks to compare turns taken.
=> Ship shots

app/controllers/api/v1/games/shots_controller.rb, app/services/turn_processor.rb, app/services/values/space.rb
Keeping track of valid/invalid shots
keeping track of ships that are sunk
starting to keep track of winners/losers
=> Invalid shots

app/controllers/api/v1/games/shots_controller.rb, app/services/turn_processor.rb
Finished the spec harness yo. Need to refactor and test.
=> Completed Spec Harness

app/controllers/api/v1/games/shots_controller.rb
Added api key validation to the game play.
=> Shots Spec

app/controllers/api/v1/games/ships_controller.rb, app/controllers/api/v1/games/shots_controller.rb, app/controllers/api/v1/games_controller.rb, app/controllers/api_controller.rb, app/services/values/ship.rb
Extracted some of the logic in the games/ships controller into api controller
Made some private methods to help with readability.
=> Refactor Games and Ships Controllers

app/controllers/api/v1/games/shots_controller.rb, app/models/game.rb
cleaned up the shots_controller a little more and added a method to the game model
=> Shots Controller Refactor

app/controllers/api/v1/games_controller.rb, spec/factories/users.rb, spec/features/user_registration_process_spec.rb, spec/models/game_spec.rb, spec/requests/shots_spec.rb, spec/requests/user_can_see_a_game_spec.rb
fixed some of the broken tests. the shots_spec needs to be changed drastically
=> Some Test Fixes

app/services/turn_processor.rb, app/services/values/space.rb
- Refactored Turn Processor. Feel free to change the methods or rename them. 
- Refactored space.rb file. Created an is_sunk? method.
- Working on the readme.
=> Refactoring

README.md
Created Readme for the project. Please let me know if you need changes.
=> Created README for the project.

app/controllers/api/v1/games/ships_controller.rb, spec/controllers/api/v1/games/ships_controller_spec.rb, spec/services/ship_placer_spec.rb
Added tests for the ships controller
Slight change in the ship_placer_spec to make it more readable
Sanitized a parameter to always come in as an integer
=> Ships Controller Tests

app/controllers/api/v1/games/shots_controller.rb, app/models/game.rb, spec/requests/shots_spec.rb
=> Fix Failing Tests

app/controllers/api/v1/games_controller.rb, app/models/game.rb, spec/models/game_spec.rb
Changed up the create_default method in an attempt to make it less hard coded.
=> Changed create_default

spec/controllers/api/v1/games/shots_controller_spec.rb
Added tests for the shots controller.
=> Shots Controller Tests
